[docs] #182 init kelee
lawnmowing-programmer/algo pull request #184
Opened 2023-03-18 03:12 UTC by lkeonwoo94

📣 Related Issue
close #182 

🌁 Background
디렉토리 및 브랜치 생성

👩‍💻 Contents
이건우/week3/2023.03.18/readme.md

📱 Screenshot
None

📝 Review Note
None

📬 Reference
None

2023-03-18 06:07 UTC, minjae9610 commented
<img width="235" alt="image" src="https://user-images.githubusercontent.com/33440010/226088187-d215c27c-cc80-4c92-b2cc-f0a5f97c6d86.png">
정보 채워주세요 :)
그리고 이슈 연결이 잘못되어있는 것 같아요 :(

2023-03-18 06:31 UTC, minjae9610 requested changes
Markdown 문법을 사용하시려고 하신거라면 이렇게 바꾸시는게 맞을 것 같습니다.

2023-03-18 06:31 UTC, minjae9610 commented on 이건우/week3/2023.03.18/README.md
> +[x] write [study env](https://github.com/lawnmowing-programmer/algo/discussions/181)
```suggestion
- [x] write [study env](https://github.com/lawnmowing-programmer/algo/discussions/181)
```

2023-03-18 06:31 UTC, minjae9610 commented on 이건우/week3/2023.03.18/README.md
> +[x] read [branch naming](https://github.com/lawnmowing-programmer/algo/discussions/6)
```suggestion
- [x] read [branch naming](https://github.com/lawnmowing-programmer/algo/discussions/6)
```

2023-03-18 06:31 UTC, minjae9610 commented on 이건우/week3/2023.03.18/README.md
> +[x] read [Others Prj dashboard](https://github.com/orgs/lawnmowing-programmer/projects/1/views/2)
```suggestion
- [x] read [Others Prj dashboard](https://github.com/orgs/lawnmowing-programmer/projects/1/views/2)
```

2023-03-18 06:31 UTC, minjae9610 commented on 이건우/week3/2023.03.18/README.md
> +[x] read [Commit convention](https://github.com/lkeonwoo94/algo/edit/main/README.md)
```suggestion
- [x] read [Commit convention](https://github.com/lkeonwoo94/algo/edit/main/README.md)
```

2023-03-18 06:35 UTC, minjae9610 approved these changes
👍

2023-03-20 13:47 UTC, closed without merging

2023-03-20 13:53 UTC, weejihye reviewed
고생하셨습니다.

2023-03-23 04:44 UTC, way-code approved these changes
수고하셨습니다!

2023-03-28 17:35 UTC, weejihye reviewed
고생하셨습니다!!