[c++]  #41 slove boj2501, boj10886
lawnmowing-programmer/algo pull request #42
Opened 2023-02-28 08:36 UTC by west-eastH

## 📣 Related Issue

close #41 

## 🌁 Background

일일 목표 달성

## 👩‍💻 Contents

- [ ] [BOJ 10886] (https://www.acmicpc.net/problem/10886)
- [ ] [BOJ 2501] (https://www.acmicpc.net/problem/2501)

## 📱 Screenshot

![boj 2501](https://user-images.githubusercontent.com/108206977/221797730-667a762d-7bda-4307-82f4-e2a0f9429827.PNG)
![boj 10886](https://user-images.githubusercontent.com/108206977/221797742-6511a549-cad5-404b-a223-b6ceec5a58e3.PNG)

## 📝 Review Note

첫 제출이라 깃허브 적응에 더 중점을 두었다.

## 📬 Reference

2023-02-28 08:40 UTC, minjae9610 commented
라벨, 프로젝트, 마일스톤 셋팅 부탁드려요!
![image](https://user-images.githubusercontent.com/33440010/221799198-d1956f68-5e3d-4f27-9ade-339e6792807f.png)

2023-02-28 08:54 UTC, minjae9610 requested changes
깔끔하게 가독성이 좋은 코드여서 너무 읽기 좋았습니다. 오랫만에 보는 c++ 임에도 잘 읽히더라구요 👍 

README.md에서 한글이 깨진것만 수정해 주시면 좋을 것 같아요 :)

2023-02-28 08:54 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj10886/README.md
> +��� : [�¾ҽ�ϴ�!!] (http://boj.kr/f781450bba8e4f0fb3ebfaff387c6d51)
텍스트 에디터 설정 때문에 한글이 깨진 것 같아요 :(

2023-02-28 08:54 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj10886/boj10886.cpp
> +		cout << "Junhee is cute!";
깔끔하게 반복 구문을 구성하신 것 같아요 👍 

yes, no 두 개의 변수가 아닌 변수 한 개 만을 이용해서 0 기준으로 양수인지 음수인지를 조건으로 걸어주는 방식으로도 해결이 가능할 것 같아요 :)

2023-02-28 08:54 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj2501/boj2501.cpp
> +	}
k 번째까지만 반복한다면 조금 더 효율적일 것 같아요 👍 

아니면 루트 n 까지만 반복문을 돌고, n mod i == 0 이면 나눠진다는 뜻이니까 몫을 저장하면 큰 수의 약수들을 구해야 할 때 시간복잡도가 줄어들지 않을까요?

2023-02-28 09:21 UTC, west-eastH commented on 서동현/week1/2023.02.27/boj10886/boj10886.cpp
> +		cout << "Junhee is cute!";
아하 다음부턴 변수를 최대한 적게 써볼게요~

2023-02-28 09:23 UTC, west-eastH commented on 서동현/week1/2023.02.27/boj2501/boj2501.cpp
> +	}
확실히 그게 더 효율적인 것 같네요. 참고하겠습니다!

2023-02-28 10:22 UTC, hsmint approved these changes
민재님이 조언하신 부분을 제외하고는 딱히 오류가 없어 보입니다. LGTM!

2023-02-28 11:19 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj10886/boj10886.cpp
> +		cout << "Junhee is cute!";
무조건 변수를 적게 쓰는게 좋은거라고는 할 수 없을때도 있으니 가독성을 생각하면서 @west-eastH 님만의 기준을 만들어보면 정말 좋을 것 같습니다 👍

2023-02-28 11:21 UTC, west-eastH commented on 서동현/week1/2023.02.27/boj10886/boj10886.cpp
> +		cout << "Junhee is cute!";
넵 근데 이거 수정하려면 vscode에서 수정하고 다시 푸쉬해야하나요?? 아니면 이 문서에서 수정할 수 있나요?

2023-02-28 11:23 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj10886/boj10886.cpp
> +		cout << "Junhee is cute!";
편하신 방법으로 하시면 됩니다. 깃헙 에디터로 수정하셔도 되고, 로컬에서 수정하셔서 푸쉬하셔도 되요!

2023-02-28 11:26 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj10886/README.md
> +��� : [�¾ҽ�ϴ�!!] (http://boj.kr/f781450bba8e4f0fb3ebfaff387c6d51)
@west-eastH 이런식으로 깃허브 상에서 새로운 커밋을 생성할 수 도 있어요!
![image](https://user-images.githubusercontent.com/33440010/221840488-4392f329-99df-4e04-bc77-d05365103c01.png)

2023-02-28 11:30 UTC, minjae9610 requested changes

2023-02-28 11:30 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj2501/README.md
> +��� : [�¾ҽ�ϴ�!!] (http://boj.kr/cd4a5b07820b45d6b3b4d39dc8bd6ac6)
이제보니까 두개 다 markdown 문법 문제로 개행이 없네요 :(
VSCode 사용하신다면 익스텐션중에 markdown 뷰어가 있던걸로 기억해요. 그거 사용하시면 보면서 바로바로 작성하실 수 있을거에요!
![image](https://user-images.githubusercontent.com/33440010/221841104-4cb9c97f-d21a-48cd-afd6-881f9cb37c42.png)

2023-02-28 11:30 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj10886/README.md
> +��� : [�¾ҽ�ϴ�!!] (http://boj.kr/f781450bba8e4f0fb3ebfaff387c6d51)
여기 개행 문제도 있어요!

2023-02-28 11:33 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj10886/boj10886.cpp
> +		cout << "Junhee is cute!";
혹시 PR 다시 작성해야 되는지에 대한 질문이었다면, PR은 merge 되기 전까지 해당 브랜치에서 발생하는 커밋의 변경사항을 지속적으로 업데이트해서 반영합니다 :)

2023-02-28 11:58 UTC, west-eastH commented on 서동현/week1/2023.02.27/boj2501/README.md
> +��� : [�¾ҽ�ϴ�!!] (http://boj.kr/cd4a5b07820b45d6b3b4d39dc8bd6ac6)
그럼 vscode에서 수정해야한다는 말씀이시죠?? 집가서 수정해보겠습니다. 수정하고 pull 요청 글도 다시 작성해야하나요?

2023-02-28 12:13 UTC, west-eastH commented on 서동현/week1/2023.02.27/boj2501/README.md
> +��� : [�¾ҽ�ϴ�!!] (http://boj.kr/cd4a5b07820b45d6b3b4d39dc8bd6ac6)
@minjae9610 수정했는데 확인 부탁드려요!

2023-02-28 12:57 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj2501/README.md
> +��� : [�¾ҽ�ϴ�!!] (http://boj.kr/cd4a5b07820b45d6b3b4d39dc8bd6ac6)
> 그럼 vscode에서 수정해야한다는 말씀이시죠?? 집가서 수정해보겠습니다. 수정하고 pull 요청 글도 다시 작성해야하나요?

위쪽에서 말씀드렸다시피 깃헙상에서 수정할수도 있고 그때는 그냥 프리뷰 보시면 됩니다

2023-02-28 13:49 UTC, minjae9610 requested changes
위쪽에 Outdate 된 conversation은 완료 처리해주세요 :)

2023-02-28 13:49 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj10886/README.md
> +[BOJ 10886 0 = not cute / 1 = cute] (https://www.acmicpc.net/problem/10886)
```suggestion
[BOJ 10886 0 = not cute / 1 = cute](https://www.acmicpc.net/problem/10886)  
```

2023-02-28 13:49 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj2501/README.md
> +[BOJ 2501 약수 구하기] (https://www.acmicpc.net/problem/2501)
```suggestion
[BOJ 2501 약수 구하기](https://www.acmicpc.net/problem/2501)  
```

2023-02-28 13:49 UTC, minjae9610 commented on 서동현/week1/2023.02.27/boj2501/README.md
> +결과 : [맞았습니다!!] (http://boj.kr/cd4a5b07820b45d6b3b4d39dc8bd6ac6)
```suggestion
결과 : [맞았습니다!!](http://boj.kr/cd4a5b07820b45d6b3b4d39dc8bd6ac6)
```

2023-02-28 14:13 UTC, minjae9610 commented
커밋 메시지가 Update README.md 인걸로봐서 깃허브 내에서 바로 수정하고 그대로 커밋하신거 같은데 그럴때에도 가급적이면 커밋 컨벤션에 맞춰봐 주시면 감사하겠습니다.

2023-02-28 14:19 UTC, west-eastH commented
수정했습니다!

2023-02-28 14:26 UTC, minjae9610 approved these changes
수많은 코드 리뷰를 버텨내셨군요! 👏
첫 머지까지 화이팅입니다.

아 그리고 저희 도큐먼트 수정 컨벤션은 [docs] 에요!
레포지토리 메인 리드미 파일에 적혀있답니다 :)

2023-03-01 09:34 UTC, minjae9610 approved these changes
LGTM

2023-03-01 10:11 UTC, merged