Algo/hsmint/2023.03.02
lawnmowing-programmer/algo pull request #78
Opened 2023-03-02 13:08 UTC by hsmint

## 📣 Related Issue

close #67, #69

## 🌁 Background

WEEK1 2022.03.02 일일 목표 달성

## 👩‍💻 Contents

Solution For
* [BOJ 11722](https://www.acmicpc.net/problem/11722)
* [BOJ 12738](https://www.acmicpc.net/problem/12738)
* [Leetcode 66](https://leetcode.com/problems/plus-one/description/)
* [Leetcode 67](https://leetcode.com/problems/add-binary/description/)

## 📱 Screenshot

![image](https://user-images.githubusercontent.com/48782012/222436742-6e1e5065-7884-4210-b277-9941afefdd4a.png)
![image](https://user-images.githubusercontent.com/48782012/222436828-fe1b2f05-b68c-4191-a0a2-9501b34b89e1.png)
![image](https://user-images.githubusercontent.com/48782012/222436888-498c43ce-0fe5-4977-83db-332d5ce365fe.png)
![image](https://user-images.githubusercontent.com/48782012/222436943-6e150813-e47b-411c-b234-44def3b14fb3.png)

## 📝 Review Note

첫 PR로 백준쪽 리드미는 비록 부족하지만 이후 내용은 더 채우도록 하겠습니다.

## 📬 Reference

2023-03-02 14:34 UTC, minjae9610 requested changes
좋은 코드 잘 봤습니다

2023-03-02 14:34 UTC, minjae9610 commented on 홍석민/week1/2022.03.02/boj11722/README.md
> +결과 : [맞았습니다!!](https://www.acmicpc.net/source/56701534)
![image](https://user-images.githubusercontent.com/33440010/222457013-5f4d5982-502a-4eaf-94db-12ec92a9ec87.png)

2023-03-02 14:34 UTC, minjae9610 commented on 홍석민/week1/2022.03.02/boj12738/README.md
> +결과 : [맞았습니다!!](https://www.acmicpc.net/source/56702637)
![image](https://user-images.githubusercontent.com/33440010/222457013-5f4d5982-502a-4eaf-94db-12ec92a9ec87.png)

2023-03-02 14:39 UTC, hsmint commented on 홍석민/week1/2022.03.02/boj11722/README.md
> +결과 : [맞았습니다!!](https://www.acmicpc.net/source/56701534)
404 좋아요 ㅎㅎ.

2023-03-02 14:40 UTC, hsmint commented on 홍석민/week1/2022.03.02/boj12738/README.md
> +결과 : [맞았습니다!!](https://www.acmicpc.net/source/56702637)
수정 완료했습니다~

2023-03-02 14:50 UTC, hsmint commented
백준 코드는 따로 공유 링크가 필요하다는 사실 처음 알았네요. ㄷㄷ

2023-03-02 14:52 UTC, minjae9610 approved these changes
깔끔한 코드 👍

2023-03-03 05:54 UTC, Hyun-Soon approved these changes
함수와 클래스를 사용해서 깔끔하게 푸신 것 같습니다

2023-03-03 08:03 UTC, merged